spring:
  application:
    name: employee-service
  profiles:
    active: mysql
  liquibase:
    change-log: classpath:db-changelog.xml
    enabled: true
#  datasource:
#    type: org.apache.tomcat.jdbc.pool.DataSource
  jpa:
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none #create-drop #none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true

logging:
  level:
    org:
      springframework: DEBUG
      springframework.boot.autoconfigure.logging: INFO

---

spring:
  datasource:
    #verifyServerCertificate=true&useSSL=true&&requireSSL=true
    url: jdbc:mysql://localhost:3306/testdb?verifyServerCertificate=true&useSSL=true&&requireSSL=true
    username: ssluser
    #password: r00tr00t
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      db-properties:
        useSSL: true
        sslMode: VERIFY_CA
        trustCertificateKeyStoreUrl: "file:/Users/dhananjay/Documents/Github/learn-spring-data/mysql-ssl/java/client-keystore.p12"
        trustCertificateKeyStorePassword: "mypass"

# To enable ssl debug pass -Djavax.net.debug=ssl:handshake:verbose

# Or Put following as VM arguments
#  -Djavax.net.ssl.trustStore=/Users/dhananjay/Documents/Github/learn-spring-data/mysql-ssl/java/client-keystore.p12
#  -Djavax.net.ssl.trustStorePassword=mypass

# For Hikari equivalent properties are
#    hikari:
#      data-source-properties:
#        useSSL: true
#        sslMode: VERIFY_CA
#        trustCertificateKeyStoreUrl: "file:/Users/dhananjay/Documents/Github/learn-spring-data/mysql-ssl/java/client-keystore.p12"
#        trustCertificateKeyStorePassword: "mypass"
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: mysql
    openInView: false
  config:
    activate:
      on-profile: mysql
