spring:
  application:
    name: employee-service
  profiles:
    active: mysql
  liquibase:
    change-log: classpath:db-changelog.xml
    enabled: true
#  datasource:
#    type: org.apache.tomcat.jdbc.pool.DataSource
  jpa:
    show_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none #create-drop #none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate.cache.use_query_cache: false
        hibernate.generate_statistics: true

logging:
  level:
    org:
      springframework: DEBUG
      springframework.boot.autoconfigure.logging: INFO

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wpdb
    username: wpuserssl
    #password: r00tr00t
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      data-source-properties:
        useSSL: true
        sslMode: VERIFY_CA
        trustCertificateKeyStoreUrl: "file:/Users/dhananjay/Downloads/mysql-ssl-docker-master/certs/truststore"
        trustCertificateKeyStorePassword: "mypass"
  jpa:
    database-platform: org.hibernate.dialect.MySQLInnoDBDialect
    database: mysql
    openInView: false
  config:
    activate:
      on-profile: mysql
