version: "3.7"
# https://docs.docker.com/compose/compose-file/

services:
  mysql:
    build: mysql-ssl
    image: mysql-ssl-local
    command: --max-allowed-packet=512M --performance-schema=FALSE --transaction-isolation=READ-COMMITTED --init-connect='SET collation_connection=utf8mb4_unicode_ci' --init-connect='SET NAMES utf8mb4;' --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci  --max-connections=500
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-ssl/config:/etc/mysql/conf.d


